### ISSUE TITLE
Crash when trying to run

### ISSUE THREAD

**Issue by KioCoan** [yopeso/Taylor#62]
Hi, I just installed Taylor via brew.

When I try running it I get:

> Illegal instruction: 4

In both Xcode and terminal.

I tried to download and run the release version, but it just crashes.
Any idea of what could it be?

I'm running on a MacBook Pro with macOS HighSierra 10.13.3
With CLI Version: 9.2.0.0.1.1510905681

**Comment by thelvis4** [comment]
Hi! 👋 Thanks for reaching out! We're investigation the issue.
In the meanwhile, can you please run `taylor -v` and confirm you're using version `0.2.3`?

**Comment by KioCoan** [comment]
Yes. I'm using the 0.2.3 version.

**Comment by KioCoan** [comment]
So.. We made it work here.

We removed the installation, then installed from the source. 
Not worked again.

After that we removed one more time and tried to install with brew as the first time.

And now it is working. 

I don't know what actually happened, but it was just an installation problem probably. 
Sorry for the inconvenience, I'm closing the issue.
